CREATE TABLE PESSOA(
  ID          INTEGER NOT NULL AUTO_INCREMENT,
  NOME                  VARCHAR(30),
  SOBRENOME             VARCHAR(20),
  ATIVO                 BIT,
  PRIMARY KEY PK_PESSOA(ID)
)ENGINE=INNODB DEFAULT CHARSET=UTF8;