CREATE TABLE PESSOA_LIVRO(
  ID                      INTEGER NOT NULL AUTO_INCREMENT,
  TITULO                  VARCHAR(30),
  NUMERO_DE_PAGINAS       VARCHAR(20),
  ATIVO                   BIT,
  ID_PESSOA               INTEGER,
  ID_LIVRO                INTEGER,
  PRIMARY KEY PK_PESSOA_LIVRO(ID),
  INDEX IDX_PESSOA_LIVRO_PESSOA_01(ID_PESSOA ),
  INDEX IDX_PESSOA_LIVRO_LIVRO_02(ID_LIVRO),
  CONSTRAINT FK_PESSOA_LIVRO_PESSOA_01 FOREIGN KEY (ID_PESSOA) REFERENCES PESSOA (ID),
  CONSTRAINT FK_PESSOA_LIVRO_LIVRO_02 FOREIGN KEY (ID_LIVRO) REFERENCES LIVRO (ID)
)ENGINE=INNODB DEFAULT CHARSET=UTF8;